language: go

go:
 - 1.6
 - 1.7
 - 1.8
 - tip

before_install:
  - go get golang.org/x/lint/golint
  - go install golang.org/x/lint/golint
  - go get golang.org/x/crypto/pbkdf2

script:
 - go build
 - go vet
 - golint
 - go test -v -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)